# Generated by Django 2.0 on 2019-11-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='name',
            new_name='lname',
        ),
        migrations.AddField(
            model_name='admin',
            name='fname',
            field=models.CharField(default='abc', max_length=50),
        ),
    ]
