# Generated by Django 2.0 on 2019-11-15 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191115_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='birthdate',
        ),
    ]
